{"body": "<p>I fixed the problem, I guess I didn't really have a solid understanding of what environmental variables are. I fixed it by just setting my aws_access_key and aws_secret_key inside of my ec2 task, below is my working playbook</p>\n\n<pre><code>- hosts: localhost  \n  connection: local  \n  gather_facts: False  \n\n  tasks:  \n    #this task creates 5 ec2 instances that are all named demo and are copies of the image specified  \n    - name: Provision a set of instances  \n      ec2:  \n         aws_access_key: .....  \n         aws_secret_key: ....  \n         key_name: .....  \n         group: .....  \n         instance_type: t2.micro  \n         image: ......  \n         region: us-east-1  \n         ec2_url: .......  \n         wait: true  \n         exact_count: 5  \n         count_tag:  \n            Name: Demo  \n         instance_tags:  \n            Name: Demo  \n      register: ec2  \n</code></pre>\n\n<p>I guess now I need to start using ansible vault to just hold my key and ID.</p>\n", "tags": ["amazon-web-services", "amazon-ec2", "ansible", "ec2-ami", "aws-ec2"], "creation_date": 1465967690, "score": 0, "last_activity_date": 1465967690, "answer_id": 37826668, "is_accepted": true, "owner": {"user_id": 5314903, "reputation": 312, "user_type": "registered", "accept_rate": 55, "display_name": "Alex Cohen", "link": "http://stackoverflow.com/users/5314903/alex-cohen", "profile_image": "https://www.gravatar.com/avatar/63b7f28e96e254a2618902d079e06dba?s=128&d=identicon&r=PG&f=1"}, "title": "msg: No handler was ready to authenticate. 1 handlers were checked. [&#39;HmacAuthV4Handler&#39;] Check your credentials", "question_id": 35748580}