{"body": "<p>Was using an outdated version of chrome driver. </p>\n\n<p>If have this issue, please check if your using latest update of the chromedriver, and the chrome browser. and be sure your using python2+</p>\n\n<p>Thank You.</p>\n", "tags": ["python-2.7", "selenium", "selenium-chromedriver", "xvfb", "httplib"], "creation_date": 1477766088, "score": 0, "last_activity_date": 1477766088, "answer_id": 40322342, "is_accepted": false, "owner": {"user_id": 4539241, "reputation": 21, "user_type": "registered", "display_name": "Kirk Douglas Jr", "link": "http://stackoverflow.com/users/4539241/kirk-douglas-jr", "profile_image": "https://www.gravatar.com/avatar/c01072fd8d0930487bcb0251abd0e6b3?s=128&d=identicon&r=PG&f=1"}, "title": "selenium chrome driver httplib.badstatusline", "question_id": 40292133}