{"answer_count": 0, "view_count": 85, "last_activity_date": 1477759220, "is_answered": false, "last_edit_date": 1471734865, "link": "http://stackoverflow.com/questions/38173690/attributeerror-dataframe-object-has-no-attribute-date", "tags": ["python-2.7", "pandas", "anaconda"], "creation_date": 1467574742, "score": 0, "title": "AttributeError: &#39;DataFrame&#39; object has no attribute &#39;date&#39;", "question_id": 38173690, "owner": {"user_id": 5005052, "reputation": 110, "user_type": "registered", "accept_rate": 50, "display_name": "Bill Ancalagon the black", "link": "http://stackoverflow.com/users/5005052/bill-ancalagon-the-black", "profile_image": "https://www.gravatar.com/avatar/a325cccf31fb0f47820cc6cfa3064772?s=128&d=identicon&r=PG&f=1"}}